server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenvanninh2004pt@gmail.com
    password: sbygkjuxqmqswjnx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  client:
    react: http://localhost:3000
    angular: http://localhost:4042
    vue_js: http://localhost:8000
  secret_key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437